### ISSUE TITLE
can not run ?

### ISSUE THREAD

**Issue by qianguozheng** [gchaincl/httplab#5]
Just git clone the repository and `go run main.go`, but it show below message

```
# command-line-arguments
./main.go:13: undefined: UI
./main.go:16: undefined: DumpRequest
./main.go:42: undefined: NewUI
```

**Comment by karianna** [comment]
I get:

```
Martijns-MBP:httplab karianna$ go run main.go
main.go:10:2: cannot find package "github.com/jroimartin/gocui" in any of:
	/opt/local/lib/go/src/github.com/jroimartin/gocui (from $GOROOT)
	/Users/karianna/go/src/github.com/jroimartin/gocui (from $GOPATH)
```

**Comment by gchaincl** [comment]
@qianguozheng if you want to use go build, you should run:
```
go run main.go dump.go response.go split.go ui.go
```

**Comment by gchaincl** [comment]
@karianna did you get the tool via `go get` or you just clone the repo, also, notice that httplab vendor its dependencies, but that should work with >=go1.6 which go version are you running?

**Comment by gchaincl** [comment]
I'm closing this, if still fails, feel free to re-open the issue.

**Comment by qianguozheng** [comment]
Thanks

**Comment by karianna** [comment]
I cloned the repo (`go get` didn't seem to do anything).  I'm using go 1.8 on Mac OS X.  I've tried `go run main.go dump.go response.go split.go ui.go` but that fails with the same error.

**Comment by gchaincl** [comment]
`go get` should have retrieved the code inside `$GOPATH/src/github.com/gchaincl/httplab` and also compile it and save the binary in `$GOPATH/bin/httplab`. Did you check there, also remember that there are binaries for darwin, check the releases

**Comment by karianna** [comment]
Hmm, for some reason that command isn't retrieving anything (and no `bin` dir) gets created.

My `echo $GOPATH` returns nothing, am I being dense and need to set that to `.`?

**Comment by gchaincl** [comment]
try to `GOPATH=~/go go get -v github.com/gchaincl/httplab` and paste the output

**Comment by karianna** [comment]
No output - I'm guessing I've got my go weirdly setup
